### ISSUE TITLE
Comma as decimal separator of quantities is ignored 

### ISSUE THREAD

**Issue by Markoise** [lneugebauer/nextcloud-cookbook#109]
In the Nextcloud Web App, you can specify quantities with a comma or a point as a decimal separator. If you increase the portion quantity here, the information is adjusted accordingly in both cases.

In your Android app, decimal separators are apparently only taken into account with a point if you want to change the portion quantity. If you enter them with an comma, the quantity will not be adjusted.

**Smartphone:**

 - Device: Pixel 7
 - OS: Android 15

**Comment by lneugebauer** [comment]
Hi @Markoise, thanks for reporting.

Can you tell me which Nextcloud and Cookbook version you are using?
I'm using Nextcloud 29 and Cookbook 0.11.2 and can not reproduce your behaviour.

I'm only able to scale the quantity using a point as a decimal separator.

![image](https://github.com/user-attachments/assets/aa9ab5c2-9c96-45cc-872c-40252993d4d1)

IIRC it was decided to use the point as a decimal separator and completely disallow thousands separators to get consistent recalculations, since different languages use different decimal and thousands separators.

**Comment by Markoise** [comment]
Hi,

I'm using Nextcloud 30.0.2 and Cookbook 0.11.2

If I enter a quantity of 1,25 in the Cookbook app, the quantity is increased accordingly when I increase the portion. The same applies if I enter 1.25 as the quantity.

In the Android app (current version via F-Droid) this only works if I enter the quantity as 1.25.
The import of the Cookbook app always imports the quantities from German recipe pages with a comma as a decimal separator. 

However, the Android app cannot handle this in my case and unfortunately ignores the portion change for these quantities.
I then manually change this to a period using the app, but as the keyboard always disappears after one character, this is almost impossible to handle.
