### ISSUE TITLE
Not possible to login if use self-signed certificate in nextcloud

### ISSUE THREAD

**Issue by AlexejHirsch** [lneugebauer/nextcloud-cookbook#15]
I have a local nextcloud instance that use a self-signed certificate. If i try to login to my nextcloud in the app i got an certificate error. I think my self-signed certificate does the issue. It is possible to ignor the self-signed certificate during the login?

**Comment by lneugebauer** [comment]
Hey @AlexejHirsch, you are right. The error is caused by your self-signed certificate. Currently its only possible to connect to Nextcloud instances with verified certificates.

Due to security reasons I didn't plan to implement this feature.

I already received a lot of feedback regarding this feature. Looks like there is a considerable demand. So I may implement this in the future - not sure yet though.

**Comment by siberianhuskies** [comment]
Hi @lneugebauer , not sure whether to open a new issue or add it here, because it is somewhat related. (Feel free to move it)

The problem also occurs when one uses its own CA to sign certificates, although the CA is added in my android phone. In this case it should just accept it. As far as I understand, Android does not trust user CAs by default (see [Changes to Trusted Certificate Authorities in Android Nougat](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html) ) but it looks like it is an easy fix.

**Comment by lneugebauer** [comment]
Hi @siberianhuskies, I think this is a great suggestion! I'll take care of implementing this in the next couple of days.
